DROP DATABASE blog_db;
CREATE DATABASE blog_db;
USE blog_db;
# DROP TABLE IF EXISTS doggos;
# DROP TABLE IF EXISTS users;
# DROP TABLE IF EXISTS posts;
# DROP TABLE IF EXISTS users;
#
# CREATE TABLE IF NOT EXISTS users (
# id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
# username VARCHAR(20) UNIQUE,
# email VARCHAR(45),
# password VARCHAR(30),
# bio TEXT,
# PRIMARY KEY (id)
# );
#
# CREATE TABLE IF NOT EXISTS posts (
# id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
# user_id INT(11) UNSIGNED NOT NULL,
# title varchar(200) DEFAULT '',
# body TEXT,
# PRIMARY KEY (id),
# FOREIGN KEY (user_id) REFERENCES users(id)
# ) ENGINE=MyISAM DEFAULT CHARSET=utf8;
#
# CREATE TABLE IF NOT EXISTS comments (
# id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
# user_id INT(11) UNSIGNED NOT NULL,
# post_id INT(11) UNSIGNED NOT NULL,
# body TEXT,
# PRIMARY KEY (id),
# FOREIGN KEY (user_id) REFERENCES users(id),
# FOREIGN KEY (post_id) REFERENCES posts(id)
# ) ENGINE=MyISAM DEFAULT CHARSET=utf8;